<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangaySeeder extends Seeder
{
    public function run(): void
    {
        $barangays = [
            ['id' => 1, 'municipality_id' => 1, 'code' => 'AB', 'name' => 'Abanao-Zandueta-Kayang-Chugum-Kayang Extension'],
            ['id' => 2, 'municipality_id' => 1, 'code' => 'AG', 'name' => 'Agupan-Loakan'],
            ['id' => 3, 'municipality_id' => 1, 'code' => 'AL', 'name' => 'Alfonso Tabora'],
            ['id' => 4, 'municipality_id' => 1, 'code' => 'AM', 'name' => 'Ambiong'],
            ['id' => 5, 'municipality_id' => 1, 'code' => 'AP', 'name' => 'Apugan-Loakan'],
            ['id' => 6, 'municipality_id' => 1, 'code' => 'AS', 'name' => 'Asin Road'],
            ['id' => 7, 'municipality_id' => 1, 'code' => 'AT', 'name' => 'Atok Trail'],
            ['id' => 8, 'municipality_id' => 1, 'code' => 'AU1', 'name' => 'Aurora Hill Proper'],
            ['id' => 9, 'municipality_id' => 1, 'code' => 'AU2', 'name' => 'Aurora Hill North Central'],
            ['id' => 10, 'municipality_id' => 1, 'code' => 'AU3', 'name' => 'Aurora Hill South Central'],
            ['id' => 11, 'municipality_id' => 1, 'code' => 'BG', 'name' => 'Baguio General Hospital'],
            ['id' => 12, 'municipality_id' => 1, 'code' => 'BK1', 'name' => 'Bakakeng Central'],
            ['id' => 13, 'municipality_id' => 1, 'code' => 'BK2', 'name' => 'Bakakeng North'],
            ['id' => 14, 'municipality_id' => 1, 'code' => 'BS', 'name' => 'Brookside'],
            ['id' => 15, 'municipality_id' => 1, 'code' => 'CA', 'name' => 'Cabinet Hill-Teacher’s Camp'],
            ['id' => 16, 'municipality_id' => 1, 'code' => 'C7', 'name' => 'Camp 7'],
            ['id' => 17, 'municipality_id' => 1, 'code' => 'C8', 'name' => 'Camp 8'],
            ['id' => 18, 'municipality_id' => 1, 'code' => 'CAL', 'name' => 'Camp Allen'],
            ['id' => 19, 'municipality_id' => 1, 'code' => 'CF', 'name' => 'Campo Filipino'],
            ['id' => 20, 'municipality_id' => 1, 'code' => 'CC', 'name' => 'Country Club Village'],
            ['id' => 21, 'municipality_id' => 1, 'code' => 'CT', 'name' => 'City Camp Central'],
            ['id' => 22, 'municipality_id' => 1, 'code' => 'ES', 'name' => 'City Camp Proper'],
            ['id' => 23, 'municipality_id' => 1, 'code' => 'CR', 'name' => 'Cresencia Village'],
            ['id' => 24, 'municipality_id' => 1, 'code' => 'DA', 'name' => 'Dagsian, Upper'],
            ['id' => 25, 'municipality_id' => 1, 'code' => 'DB', 'name' => 'Dagsian, Lower'],
            ['id' => 26, 'municipality_id' => 1, 'code' => 'DP', 'name' => 'Dizon Subdivision'],
            ['id' => 27, 'municipality_id' => 1, 'code' => 'DO', 'name' => 'Dominican Hill-Mirador'],
            ['id' => 28, 'municipality_id' => 1, 'code' => 'DM', 'name' => 'Dontogan'],
            ['id' => 29, 'municipality_id' => 1, 'code' => 'EP', 'name' => 'Engineers\' Hill'],
            ['id' => 30, 'municipality_id' => 1, 'code' => 'FA', 'name' => 'Fairview Village'],
            ['id' => 31, 'municipality_id' => 1, 'code' => 'FE', 'name' => 'Ferdinand (Happy Homes-Campo Sioco)'],
            ['id' => 32, 'municipality_id' => 1, 'code' => 'FS', 'name' => 'Fort del Pilar'],
            ['id' => 33, 'municipality_id' => 1, 'code' => 'GI', 'name' => 'Gibraltar'],
            ['id' => 34, 'municipality_id' => 1, 'code' => 'GN', 'name' => 'General Luna, Upper'],
            ['id' => 35, 'municipality_id' => 1, 'code' => 'GL', 'name' => 'General Luna, Lower'],
            ['id' => 36, 'municipality_id' => 1, 'code' => 'GS', 'name' => 'Greenwater Village'],
            ['id' => 37, 'municipality_id' => 1, 'code' => 'GR', 'name' => 'Guisad Central'],
            ['id' => 38, 'municipality_id' => 1, 'code' => 'GA', 'name' => 'Guisad Surong'],
            ['id' => 39, 'municipality_id' => 1, 'code' => 'GH', 'name' => 'Happy Hollow'],
            ['id' => 40, 'municipality_id' => 1, 'code' => 'HR', 'name' => 'Harrison-Claudio Carantes'],
            ['id' => 41, 'municipality_id' => 1, 'code' => 'HR2', 'name' => 'Hillside'],
            ['id' => 42, 'municipality_id' => 1, 'code' => 'IM', 'name' => 'Imelda Village'],
            ['id' => 43, 'municipality_id' => 1, 'code' => 'IN', 'name' => 'Inabaan'],
            ['id' => 44, 'municipality_id' => 1, 'code' => 'IR', 'name' => 'Irisan'],
            ['id' => 45, 'municipality_id' => 1, 'code' => 'JO', 'name' => 'Josefa Carino'],
            ['id' => 46, 'municipality_id' => 1, 'code' => 'KB', 'name' => 'Kabayanihan'],
            ['id' => 47, 'municipality_id' => 1, 'code' => 'KH', 'name' => 'Kias'],
            ['id' => 48, 'municipality_id' => 1, 'code' => 'KR', 'name' => 'Kayang Extension'],
            ['id' => 49, 'municipality_id' => 1, 'code' => 'KZ', 'name' => 'Kayang-Hilltop'],
            ['id' => 50, 'municipality_id' => 1, 'code' => 'KS', 'name' => 'Kisad Road'],
            ['id' => 51, 'municipality_id' => 1, 'code' => 'LA', 'name' => 'Lourdes Subdivision Extension'],
            ['id' => 52, 'municipality_id' => 1, 'code' => 'LB', 'name' => 'Lourdes Subdivision Proper'],
            ['id' => 53, 'municipality_id' => 1, 'code' => 'LI', 'name' => 'Liwanag-Loakan'],
            ['id' => 54, 'municipality_id' => 1, 'code' => 'LM', 'name' => 'Loakan Proper'],
            ['id' => 55, 'municipality_id' => 1, 'code' => 'LN', 'name' => 'Loakan-Apugan'],
            ['id' => 56, 'municipality_id' => 1, 'code' => 'LU', 'name' => 'Lucnab'],
            ['id' => 57, 'municipality_id' => 1, 'code' => 'LU2', 'name' => 'Lualhati'],
            ['id' => 58, 'municipality_id' => 1, 'code' => 'MA', 'name' => 'Magsaysay Private Road'],
            ['id' => 59, 'municipality_id' => 1, 'code' => 'MB', 'name' => 'Magsaysay Upper'],
            ['id' => 60, 'municipality_id' => 1, 'code' => 'MC', 'name' => 'Magsaysay Lower'],
            ['id' => 61, 'municipality_id' => 1, 'code' => 'MH', 'name' => 'Malcolm Square-Perfecto'],
            ['id' => 62, 'municipality_id' => 1, 'code' => 'MN', 'name' => 'Malvar-Sgt. Floresca'],
            ['id' => 63, 'municipality_id' => 1, 'code' => 'MO', 'name' => 'Market Subdivision'],
            ['id' => 64, 'municipality_id' => 1, 'code' => 'MR', 'name' => 'Middle Rock Quarry'],
            ['id' => 65, 'municipality_id' => 1, 'code' => 'MT', 'name' => 'Mines View Park'],
            ['id' => 66, 'municipality_id' => 1, 'code' => 'NA', 'name' => 'Navy Base'],
            ['id' => 67, 'municipality_id' => 1, 'code' => 'NC', 'name' => 'New Lucban'],
            ['id' => 68, 'municipality_id' => 1, 'code' => 'NH', 'name' => 'North Central Aurora Hill'],
            ['id' => 69, 'municipality_id' => 1, 'code' => 'NO', 'name' => 'North Sanitary Camp'],
            ['id' => 70, 'municipality_id' => 1, 'code' => 'ON', 'name' => 'Outlook Drive'],
            ['id' => 71, 'municipality_id' => 1, 'code' => 'PA', 'name' => 'Pacdal'],
            ['id' => 72, 'municipality_id' => 1, 'code' => 'PB', 'name' => 'Padre Burgos'],
            ['id' => 73, 'municipality_id' => 1, 'code' => 'PC', 'name' => 'Padre Zamora'],
            ['id' => 74, 'municipality_id' => 1, 'code' => 'PE', 'name' => 'P. Burgos'],
            ['id' => 75, 'municipality_id' => 1, 'code' => 'PF', 'name' => 'Pinget'],
            ['id' => 76, 'municipality_id' => 1, 'code' => 'PG', 'name' => 'Pinesville Subdivision'],
            ['id' => 77, 'municipality_id' => 1, 'code' => 'PH', 'name' => 'Phil-Am'],
            ['id' => 78, 'municipality_id' => 1, 'code' => 'PI', 'name' => 'Pinsao Pilot Project'],
            ['id' => 79, 'municipality_id' => 1, 'code' => 'PJ', 'name' => 'Pinsao Proper'],
            ['id' => 80, 'municipality_id' => 1, 'code' => 'PK', 'name' => 'Pinget Extension'],
            ['id' => 81, 'municipality_id' => 1, 'code' => 'PL', 'name' => 'P. Lucban'],
            ['id' => 82, 'municipality_id' => 1, 'code' => 'PM', 'name' => 'Quirino Hill, East'],
            ['id' => 83, 'municipality_id' => 1, 'code' => 'PN', 'name' => 'Quirino Hill, West'],
            ['id' => 84, 'municipality_id' => 1, 'code' => 'PO', 'name' => 'Quirino Hill, Middle'],
            ['id' => 85, 'municipality_id' => 1, 'code' => 'PP', 'name' => 'Quezon Hill, Upper'],
            ['id' => 86, 'municipality_id' => 1, 'code' => 'PQ', 'name' => 'Quezon Hill, Lower'],
            ['id' => 87, 'municipality_id' => 1, 'code' => 'PR', 'name' => 'Quezon Hill, Middle'],
            ['id' => 88, 'municipality_id' => 1, 'code' => 'PS', 'name' => 'Pinget Subdivision'],
            ['id' => 89, 'municipality_id' => 1, 'code' => 'PT', 'name' => 'Poliwes'],
            ['id' => 90, 'municipality_id' => 1, 'code' => 'PU', 'name' => 'Pucsusan'],
            ['id' => 91, 'municipality_id' => 1, 'code' => 'PV', 'name' => 'Purok 1'],
            ['id' => 92, 'municipality_id' => 1, 'code' => 'PW', 'name' => 'Purok 2'],
            ['id' => 93, 'municipality_id' => 1, 'code' => 'PX', 'name' => 'Purok 3'],
            ['id' => 94, 'municipality_id' => 1, 'code' => 'PY', 'name' => 'Purok 4'],
            ['id' => 95, 'municipality_id' => 1, 'code' => 'PZ', 'name' => 'Purok 5'],
            ['id' => 96, 'municipality_id' => 1, 'code' => 'QA', 'name' => 'Quirino Hill Proper'],
            ['id' => 97, 'municipality_id' => 1, 'code' => 'QB', 'name' => 'Rock Quarry, Middle'],
            ['id' => 98, 'municipality_id' => 1, 'code' => 'QC', 'name' => 'Rock Quarry, Lower'],
            ['id' => 99, 'municipality_id' => 1, 'code' => 'QD', 'name' => 'Rock Quarry, Upper'],
            ['id' => 100, 'municipality_id' => 1, 'code' => 'QE', 'name' => 'Rizal Monument Area'],
            ['id' => 101, 'municipality_id' => 1, 'code' => 'QF', 'name' => 'Saint Joseph Village'],
            ['id' => 102, 'municipality_id' => 1, 'code' => 'QG', 'name' => 'Salud Mitra'],
            ['id' => 103, 'municipality_id' => 1, 'code' => 'QH', 'name' => 'San Antonio Village'],
            ['id' => 104, 'municipality_id' => 1, 'code' => 'QI', 'name' => 'San Luis Village'],
            ['id' => 105, 'municipality_id' => 1, 'code' => 'QJ', 'name' => 'San Roque Village'],
            ['id' => 106, 'municipality_id' => 1, 'code' => 'QK', 'name' => 'San Vicente'],
            ['id' => 107, 'municipality_id' => 1, 'code' => 'QL', 'name' => 'Santa Escolastica Village'],
            ['id' => 108, 'municipality_id' => 1, 'code' => 'QM', 'name' => 'Santo Rosario Valley'],
            ['id' => 109, 'municipality_id' => 1, 'code' => 'QN', 'name' => 'Scout Barrio'],
            ['id' => 110, 'municipality_id' => 1, 'code' => 'QO', 'name' => 'Slaughterhouse Compound'],
            ['id' => 111, 'municipality_id' => 1, 'code' => 'QP', 'name' => 'South Drive'],
            ['id' => 112, 'municipality_id' => 1, 'code' => 'QQ', 'name' => 'Sto. Tomas Proper'],
            ['id' => 113, 'municipality_id' => 1, 'code' => 'QR', 'name' => 'Sto. Tomas School Area'],
            ['id' => 114, 'municipality_id' => 1, 'code' => 'QS', 'name' => 'Teodora Alonzo'],
            ['id' => 115, 'municipality_id' => 1, 'code' => 'QT', 'name' => 'Trancoville'],
            ['id' => 116, 'municipality_id' => 1, 'code' => 'QU', 'name' => 'Victoria Village'],
            ['id' => 117, 'municipality_id' => 1, 'code' => 'QV', 'name' => 'West Modernsite, Aurora Hill'],
            ['id' => 118, 'municipality_id' => 1, 'code' => 'QW', 'name' => 'West Quirino Hill'],
            ['id' => 119, 'municipality_id' => 1, 'code' => 'QX', 'name' => 'West Irisan'],
            ['id' => 120, 'municipality_id' => 1, 'code' => 'QY', 'name' => 'West Bayanihan'],
            ['id' => 121, 'municipality_id' => 1, 'code' => 'QZ', 'name' => 'West Lualhati'],
            ['id' => 122, 'municipality_id' => 1, 'code' => 'RA', 'name' => 'West Bakakeng'],
            ['id' => 123, 'municipality_id' => 1, 'code' => 'RB', 'name' => 'West Upper Quirino'],
            ['id' => 124, 'municipality_id' => 1, 'code' => 'RC', 'name' => 'Woodsgate Subdivision'],
            ['id' => 125, 'municipality_id' => 1, 'code' => 'RD', 'name' => 'Happy Homes'],
            ['id' => 126, 'municipality_id' => 1, 'code' => 'RE', 'name' => 'Middle Quirino'],
            ['id' => 127, 'municipality_id' => 1, 'code' => 'RF', 'name' => 'Honeymoon-Holyghost'],
            ['id' => 128, 'municipality_id' => 1, 'code' => 'RG', 'name' => 'Magsaysay Hill'],
            ['id' => 129, 'municipality_id' => 1, 'code' => 'RH', 'name' => 'Upper Magsaysay Hill'],
        ];

        DB::table('barangays')->insert($barangays);
    }
}
